all_ssl_password: "{{vault_ssl_password}}" #Custom to these script to access vault simplier
pkcs12_enabled: false #Optional to use PKSC12 over JKS

#Used by both Customer Certs and 
ssl_keystore_key_password: "{{all_ssl_password}}"
ssl_keystore_store_password: "{{all_ssl_password}}"
ssl_truststore_password: "{{all_ssl_password}}"

#Use provided Certs
ssl_custom_certs: true #If True to take certs and create keystore and truststore
ssl_ca_cert_filepath: "ssl-certs/casnakeoil.crt"
ssl_signed_cert_filepath: "ssl-certs/{{inventory_hostname}}.crt"
ssl_key_filepath: "ssl-certs/{{inventory_hostname}}.key"
ssl_key_password: "{{all_ssl_password}}"

#Use provide Key and Truststores
ssl_provided_keystore_and_truststore: false #If true provide the keystores
ssl_keystore_filepath: "ssl-certs/{{inventory_hostname}}.keystore.jks"
ssl_truststore_filepath: "ssl-certs/{{inventory_hostname}}.truststore.jks"

kafka_broker_default_listeners: 
  internal:
    ssl_enabled: true #SSL can be enabled directly here or by defining ssl_enabled globally
    
control_center_ssl_enabled: false #This is disabled in order to get Chrome to work with self signed certs
ksql_ssl_enabled: true
kafka_connect_ssl_enabled: true
kafka_rest_ssl_enabled: true
schema_registry_ssl_enabled: true