all:
  hosts:
    ccc1.dc1.nikoleta.aws.ps.confluent.io:
    ccc1.dc2.nikoleta.aws.ps.confluent.io:
    zk[1:3].dc1.nikoleta.aws.ps.confluent.io:
    zk[1:3].dc2.nikoleta.aws.ps.confluent.io:
    kfk[1:3].dc1.nikoleta.aws.ps.confluent.io:
    kfk[1:3].dc2.nikoleta.aws.ps.confluent.io:
    sr[1:2].dc1.nikoleta.aws.ps.confluent.io:
    sr[1:2].dc2.nikoleta.aws.ps.confluent.io:
    connect[1:2].dc1.nikoleta.aws.ps.confluent.io:
    connect[1:2].dc2.nikoleta.aws.ps.confluent.io:
    ksql[1:2].dc1.nikoleta.aws.ps.confluent.io:
    ksql[1:2].dc2.nikoleta.aws.ps.confluent.io:
    ccc1.nikoleta.aws.ps.confluent.io:
    zk[1:3].nikoleta.aws.ps.confluent.io:
    kfk[1:3].nikoleta.aws.ps.confluent.io:
    sr[1:2].nikoleta.aws.ps.confluent.io:
    connect[1:2].nikoleta.aws.ps.confluent.io:
    ksql[1:2].nikoleta.aws.ps.confluent.io:
    