kafka_broker_default_listeners: 
   internal:
     name: INTERNAL
     ssl_enabled: false
     sasl_protocol: scram
     ssl_mutual_auth_enabled: false
     port: 9093
      
# This setting is not required as the above will cover most tradition of use cases. 
# This is included here to assist with the other install types that need multipule interfaces.       
kafka_broker_custom_listeners: 
  external:
    name: EXTERNAL
    ssl_enabled: false
    sasl_protocol: SCRAM
    ssl_mutual_auth_enabled: false
    port: 9092

# Not required to be defined as this is the default values.
# It is shown here for documentation and reference.
sasl_scram_users:
  admin:
    principal: admin
    password: admin-secret
  client:
    principal: client
    password: client-secret
  kafka_connect:
    principal: kafka_connect
    password: kafka_connect-secret
  control_center:
    principal: control_center
    password: control_center-secret
  kafka_rest:
    principal: kafka_rest
    password: kafka_rest-secret
  ksql:
    principal: ksql
    password: ksql-secret
  schema_registry:
    principal: schema_registry
    password: schema_registry-secret